Add query for regional breakdown
collective-service/ifrc-gates-dashboard pull request #106
Opened 2022-09-15 08:24 UTC by priyesh777

## Addresses:

## Changes:
- Add query changes to regional breakdown
- Add tooltip for pie chart component

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-09-19 11:36 UTC, subinasr requested changes

2022-09-19 11:36 UTC, subinasr commented on app/views/Dashboard/Overview/PercentageCardGroup/index.tsx
> +`;
Why are we calling the same queries twice? Can we merge this into a same query?

2022-09-19 11:36 UTC, subinasr commented on app/views/Dashboard/Overview/PercentageCardGroup/index.tsx
> +`;
This too!

2022-09-20 04:28 UTC, AdityaKhatri requested changes

2022-09-20 04:28 UTC, AdityaKhatri commented on app/views/Dashboard/Country/index.tsx
> +                isTwelveMonth: $isTwelveMonth,
if always true, directly set true.

2022-09-20 04:28 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/PercentageCardGroup/index.tsx
>  }
Move props closer to function

2022-09-20 04:28 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/PercentageCardGroup/index.tsx
> +
remove empty line

2022-09-20 04:28 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/PercentageCardGroup/index.tsx
> +        }
fix indent plz

2022-09-20 04:28 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/PercentageCardGroup/index.tsx
> +
use useCallback

2022-09-20 04:28 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/PercentageCardGroup/styles.css
> +        flex-basis: calc(35% - var(--dui-spacing-small));
sir maths

2022-09-20 05:13 UTC, shreeyash07 approved these changes

2022-09-20 05:47 UTC, shreeyash07 commented on app/views/Dashboard/Country/index.tsx
> +                isTwelveMonth: $isTwelveMonth,
It may vary in some cases in future

2022-09-20 06:02 UTC, subinasr approved these changes

2022-09-20 06:42 UTC, merged