Use skip for query optimization
collective-service/ifrc-gates-dashboard pull request #155
Opened 2022-09-28 05:54 UTC by subinasr

- Depends on server branch feature/add-description-fields-in-region-level-and-global-level

## Changes

* Fix apollo to support 'skip'
* Query optimization

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-09-28 06:25 UTC, shreeyash07 requested changes

2022-09-28 06:25 UTC, shreeyash07 commented on app/views/Dashboard/index.tsx
> +        activeTab,
Remove Blank Line

2022-09-28 06:26 UTC, shreeyash07 approved these changes

2022-09-28 06:54 UTC, priyesh777 approved these changes

2022-09-28 06:54 UTC, priyesh777 commented on app/views/Dashboard/Overview/MapView/index.tsx
> +        data: pulledData,
I guess we can rename this "pulledData" to something specific

2022-09-29 04:10 UTC, priyesh777 approved these changes

2022-09-29 06:44 UTC, AdityaKhatri approved these changes

2022-09-29 06:44 UTC, merged