Add fixes for map tool-tip and components
collective-service/ifrc-gates-dashboard pull request #200
Opened 2022-10-12 09:54 UTC by priyesh777

## Addresses:
- Task: https://github.com/collective-service/ifrc-gates-dashboard/issues/186
- Task: https://github.com/collective-service/ifrc-gates-dashboard/issues/185
-Task: https://github.com/collective-service/ifrc-gates-dashboard/issues/117

## Changes:
- Add fixes to map tool-tip and other components of map/
- Add changes to map sub-header component 

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-10-12 11:08 UTC, shreeyash07 approved these changes

2022-10-17 06:14 UTC, subinasr requested changes

2022-10-17 06:14 UTC, subinasr commented on app/views/Dashboard/Overview/MapView/index.tsx
> +    indicatorValue: OverviewMapDataType | undefined;
I don't think this is correct. Can you please verify?

2022-10-17 06:14 UTC, subinasr commented on app/views/Dashboard/Overview/MapView/index.tsx
> +                        precision="auto"
```suggestion
                        precision={1}
```

2022-10-17 06:14 UTC, subinasr commented on app/views/Dashboard/Overview/MapView/index.tsx
> +    // Note: This sorting logic maybe required in future
```suggestion
    // NOTE: This sorting logic maybe required in future
```

2022-10-17 06:14 UTC, subinasr commented on app/views/Dashboard/Overview/index.tsx
> +    return 'Total number of cases by country';
```suggestion
    return 'New cases per million by country';
```

2022-10-17 06:14 UTC, subinasr commented on app/views/Dashboard/Overview/index.tsx
> +function Overview(props: OverViewProps) {
Why??

2022-10-17 06:14 UTC, subinasr commented on app/views/Dashboard/Overview/index.tsx
> +                                : 'Total number of cases by country')}
Doesn't MapSubHeader function handle the case of no filterValues?

2022-10-17 09:06 UTC, subinasr approved these changes

2022-10-17 10:52 UTC, merged