Add reusable stat component
collective-service/ifrc-gates-dashboard pull request #22
Opened 2022-07-25 08:55 UTC by priyesh777

## Changes:
- Add reusable component such as status card which is used both in overview and country section

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-07-25 10:11 UTC, AdityaKhatri requested changes

2022-07-25 10:11 UTC, AdityaKhatri commented on app/components/ProgressBar/index.tsx
> +        ), [data],
```suggestion
        ),
        [data],
```

2022-07-25 10:11 UTC, AdityaKhatri commented on app/components/ProgressBar/index.tsx
> +        <>
Unncessary nesting

2022-07-25 10:11 UTC, AdityaKhatri commented on app/components/ProgressBar/index.tsx
> +                    })}
Use list

2022-07-25 10:11 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/MapView/index.tsx
> +                    ))}
Use listview

2022-07-25 10:11 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/MapView/index.tsx
> +                    ))}
Use listview

2022-07-25 10:11 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/TableView/index.tsx
> +            <ContainerCard>
use only ContainerCard

2022-07-28 04:14 UTC, shreeyash07 approved these changes

2022-07-28 04:39 UTC, shreeyash07 approved these changes

2022-07-28 07:58 UTC, shreeyash07 approved these changes

2022-07-28 08:46 UTC, AdityaKhatri requested changes

2022-07-28 08:46 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/MapView/index.tsx
> +                        bounds={[80.088425, 26.397898, 88.174804, 30.422717]}
define this outside

2022-07-28 09:32 UTC, AdityaKhatri approved these changes

2022-07-28 09:33 UTC, merged