Change 0 to <1 if value is less than 0.9999
collective-service/ifrc-gates-dashboard pull request #469
Opened 2022-12-16 09:02 UTC by shreeyash07

- Addresses #449 

## Changes

* Change 0 to <1 in bar label list and pass nonNormalizedValue in regional Breakdown chart
* Change 0 to <1 in progress bar and change value in tooltip

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-12-19 05:04 UTC, priyesh777 approved these changes

2022-12-22 09:47 UTC, priyesh777 approved these changes

2022-12-27 10:20 UTC, subinasr approved these changes

2022-12-27 10:20 UTC, subinasr commented on app/utils/common.ts
> +    if (value < 0.999) {
```suggestion
    if (value < 1) {
```

2022-12-27 10:20 UTC, subinasr commented on app/components/PercentageStats/index.tsx
> +    // FIXME: use isNotDefined
Let's fix this!

2022-12-27 10:20 UTC, subinasr commented on app/components/CustomTooltip/index.tsx
>              (acc, obj) => (acc + (obj?.contextIndicatorValue ?? 1)), 0,
Why is the value 1 here?

2022-12-27 10:21 UTC, subinasr requested changes

2022-12-27 10:21 UTC, subinasr commented on app/components/CustomTooltip/index.tsx
>              (acc, obj) => (acc + (obj?.contextIndicatorValue ?? 1)), 0,
.

2022-12-27 10:21 UTC, subinasr reviewed
Please fix the comments.

2022-12-28 04:31 UTC, merged