Add form handlers for filters
collective-service/ifrc-gates-dashboard pull request #65
Opened 2022-08-16 10:17 UTC by subinasr

## Changes

* Add form handlers for filters and advanced filters

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-08-16 10:28 UTC, shreeyash07 approved these changes

2022-08-18 05:32 UTC, priyesh777 approved these changes

2022-08-19 06:35 UTC, AdityaKhatri requested changes

2022-08-19 06:35 UTC, AdityaKhatri commented on app/views/Dashboard/AdvancedFilters/index.tsx
> +    keywords?: string[] | undefined;
? and undefined both together don't make sense.

2022-08-19 06:35 UTC, AdityaKhatri commented on app/views/Dashboard/Filters/index.tsx
> +    country?: string | undefined;
same as above

2022-08-19 08:02 UTC, merged