Add changes to card components
collective-service/ifrc-gates-dashboard pull request #76
Opened 2022-08-18 05:28 UTC by priyesh777

## Addresses:
- Task: https://github.com/collective-service/ifrc-gates-dashboard/issues/14

## Changes:
- Add style changes to the overview components
- Implementation of table component

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-08-23 04:16 UTC, shreeyash07 requested changes

2022-08-23 04:16 UTC, shreeyash07 commented on app/views/Dashboard/Overview/PercentageCardGroup/styles.css
> +        flex-grow: 1;
If not needed remove comments

2022-08-23 08:19 UTC, shreeyash07 approved these changes

2022-08-23 08:26 UTC, subinasr approved these changes

2022-08-24 04:18 UTC, shreeyash07 approved these changes

2022-08-25 08:20 UTC, merged