Add uncertainty chart in the over-view section
collective-service/ifrc-gates-dashboard pull request #81
Opened 2022-08-24 11:18 UTC by priyesh777

- Addresses XXX

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

2022-08-31 08:46 UTC, shreeyash07 commented on app/components/PercentageStats/index.tsx
> +            heading={heading ? `${heading}` : 'Total number of cases'}
Revert it back

2022-08-31 10:00 UTC, priyesh777 commented on app/components/PercentageStats/index.tsx
> +            heading={heading ? `${heading}` : 'Total number of cases'}
Done

2022-08-31 10:01 UTC, shreeyash07 approved these changes

2022-08-31 10:07 UTC, shreeyash07 approved these changes

2022-09-01 05:13 UTC, AdityaKhatri requested changes

2022-09-01 05:13 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/MapView/MapModal/index.tsx
> +            footer={<ModalFooterElement />}
Why do this?
Please put it directly here

2022-09-01 05:13 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/index.tsx
> +        console.log('Handle map modal:::>>>>>', mapModalShown);
remove this. Also, we can directly use setMapModalVisible in the function.
Also, rename setMapModalVisible to showMapModal

2022-09-02 04:01 UTC, shreeyash07 approved these changes

2022-09-02 05:13 UTC, subinasr requested changes

2022-09-02 05:13 UTC, subinasr commented on app/utils/hooks/stateManagement.ts
> +export function useModalState(initialValue: boolean): [
Why not import 'useModalState' directly from 'deep-ui' ?

2022-09-02 05:17 UTC, priyesh777 commented on app/utils/hooks/stateManagement.ts
> +export function useModalState(initialValue: boolean): [
This has been replaced by the useModalState of deep-ui

2022-09-02 06:45 UTC, shreeyash07 approved these changes

2022-09-02 08:17 UTC, AdityaKhatri approved these changes

2022-09-02 09:21 UTC, merged