Country - fetch data
collective-service/ifrc-gates-dashboard pull request #88
Opened 2022-08-31 08:43 UTC by shreeyash07

- Addresses 
- #37 
- #86 

## Changes
- Fetched country details data
- Fetched disaggregation data
- small css changes

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-08-31 11:11 UTC, priyesh777 approved these changes

2022-09-01 05:01 UTC, subinasr requested changes

2022-09-01 05:01 UTC, subinasr commented on app/views/Dashboard/Country/index.tsx
> +        iso3: filterValues?.country ?? 'NPL',
Why? I thought they wanted a country on top of the list to be selected as default, which is 'AFG'.
If this is a temporary thing, please add a 'NOTE' to remind you to revert it back in the final stage.

2022-09-01 05:01 UTC, subinasr commented on app/views/Dashboard/Country/index.tsx
> +                fill: COLORS[index % COLORS.length] ?? 'green',
Why 'green'? Please use relevant colors.

2022-09-01 05:01 UTC, subinasr commented on app/views/Dashboard/Country/index.tsx
> +                fill: COLORS[index % COLORS.length] ?? 'green',
same here

2022-09-01 05:01 UTC, subinasr commented on app/views/Dashboard/Country/index.tsx
> +interface legend {
```suggestion
interface Legend {
```

2022-09-01 05:01 UTC, subinasr commented on app/views/Dashboard/Country/index.tsx
> +                                Regional 30%
Let's add a note here so that we don't forget to put in regional data from the API.

2022-09-01 05:24 UTC, AdityaKhatri requested changes

2022-09-01 05:24 UTC, AdityaKhatri commented on app/views/Dashboard/Country/index.tsx
> +            contextResponse?.contextualData || [],
```suggestion
            contextResponse?.contextualData ?? [],
```

2022-09-01 05:24 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/OverviewTable/index.tsx
> +    const { ...otherProps } = props;
Lets, tara lets not.

2022-09-01 06:42 UTC, priyesh777 commented on app/views/Dashboard/CombinedIndicators/styles.css
> +        padding: var(--spacing);
I guess the padding here doesn't make sense

2022-09-01 08:12 UTC, priyesh777 approved these changes

2022-09-02 08:23 UTC, AdityaKhatri requested changes

2022-09-02 08:23 UTC, AdityaKhatri commented on app/views/Dashboard/Country/index.tsx
> +        };
sort((a, b) => compareDate(a.contextDate, b.contextDate))

2022-09-02 08:23 UTC, AdityaKhatri commented on app/views/Dashboard/Overview/OverviewTable/index.tsx
> +        <div className={_cs(className, (value && +(value) > 40 && styles.highIndicator))}>
put logic outside

2022-09-05 08:42 UTC, AdityaKhatri commented on app/views/Dashboard/Country/index.tsx
> +            items.sort((a, b) => Number(a.contextDate) - Number(b.contextDate));
```suggestion
            items.sort((a, b) => compareDate(a.contextDate, b.contextDate));
```

2022-09-05 09:18 UTC, tnagorra requested changes

2022-09-05 09:18 UTC, tnagorra commented on app/components/CustomLegend/index.tsx
> +    genders?: string;
```suggestion
    gender?: string;
```

2022-09-05 09:18 UTC, tnagorra commented on app/components/CustomLegend/index.tsx
> +                {/* FIX ME: Add regional data */}
```suggestion
                {/* FIXME: Add regional data */}
```

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/CombinedIndicators/styles.css
> +        background-color: white;
Let's use a css variable

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +interface EmergencyItems {
Lets move this before CountryWiseOutbreakCases

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +    const countryVariables = useMemo(() => ({
```suggestion
    const countryVariables = useMemo((): CountryQueryVariables => ({
```

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +        const latestDateItems = (items: EmergencyItems[]) => {
```suggestion
        const getLatestDateItems = (items: EmergencyItems[]) => {
```

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +            items.sort((a, b) => compareDate(a.contextDate, b.contextDate, -1));
`sort` mutates the list so let's make a copy

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +                    key: `${emergency}`,
```suggestion
                    key: emergency,
```

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +                        ),
Let's define a utility function

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +        unique(
Let's define a FIXME to remove these unique

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +        unique(
Let's define a FIXME to remove these unique

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +                key: `${item.category}${item.indicatorValue}`,
```suggestion
                key: `${item.category}-${item.indicatorValue}`,
```

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +                key: `${item.category}${item.indicatorValue}`,
```suggestion
                key: `${item.category}-${item.indicatorValue}`,
```

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +    const ageCustomLegend = (legendData: CustomLegendProps[]) => (
We do not need to create a function.

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +                                            value={`${internetAccessRegion}%`}
Let's check if this value is defined or not.

2022-09-05 09:18 UTC, tnagorra commented on app/views/Dashboard/Country/index.tsx
> +                                                ?.toFixed(0)}
```suggestion
                                                ?.toFixed(2)}
```

2022-09-05 09:21 UTC, shreeyash07 commented on app/components/CustomLegend/index.tsx
> +    genders?: string;
done

2022-09-05 09:22 UTC, shreeyash07 commented on app/components/CustomLegend/index.tsx
> +                {/* FIX ME: Add regional data */}
Done

2022-09-05 09:23 UTC, shreeyash07 commented on app/views/Dashboard/CombinedIndicators/styles.css
> +        background-color: white;
Done

2022-09-05 10:23 UTC, AdityaKhatri approved these changes

2022-09-05 10:26 UTC, merged