Add indicator filter options
collective-service/ifrc-gates-dashboard pull request #89
Opened 2022-08-31 09:33 UTC by subinasr

## Changes

* Add indicator filter options

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-08-31 09:52 UTC, shreeyash07 approved these changes

2022-09-01 05:09 UTC, AdityaKhatri requested changes

2022-09-01 05:09 UTC, AdityaKhatri commented on app/views/Dashboard/Filters/index.tsx
> +                        disabled={activeTab === 'country' ? indicatorsLoading : globalIndicatorsLoading}
separate this out

2022-09-01 05:18 UTC, priyesh777 approved these changes

2022-09-02 08:24 UTC, AdityaKhatri approved these changes

2022-09-02 08:26 UTC, merged