Add filters and advanced filters options
collective-service/ifrc-gates-dashboard pull request #96
Opened 2022-09-09 05:42 UTC by subinasr

- Addresses #57 #60 #59 #62 
- Depends on server branch fix/combined-indicator-options

## Changes

*  Add filter options
* Add a clear button to clear the filters
* Add advanced filter options
* Keywords list pending (last minute changes)

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-09-09 05:52 UTC, shreeyash07 approved these changes

2022-09-09 06:15 UTC, priyesh777 approved these changes

2022-09-09 06:22 UTC, AdityaKhatri commented on app/views/Dashboard/AdvancedFilters/index.tsx
> +
Why not pull this together with other gql queries that run on mount?
Lets!

2022-09-09 06:24 UTC, AdityaKhatri requested changes

2022-09-09 06:24 UTC, AdityaKhatri commented on app/views/Dashboard/AdvancedFilters/index.tsx
>  }
Use generic or from the gql query?

2022-09-09 06:24 UTC, AdityaKhatri commented on app/views/Dashboard/AdvancedFilters/index.tsx
> +    const types = typeList?.filterOptions?.types.map((t) => ({
what is t? Please write full name plz

2022-09-10 11:25 UTC, AdityaKhatri requested changes

2022-09-10 11:25 UTC, AdityaKhatri commented on app/views/Dashboard/Filters/index.tsx
> +    }));
use use memo

2022-09-10 11:31 UTC, merged